import Head from "next/head"
import NavBar from "@/components/common/NavBar"
import FooterBar from "@/components/common/Footer"
import HeroSection from "@/components/common/HeroSection"
import CompanySlider from "@/components/common/CompanySlider"
import Insight from "@/components/common/Insight"
import WayFromIdea from "@/components/common/WayFromIdea"
import GainInsight from "@/components/common/GainInsight"
import PowerOfData from "@/components/common/PowerOfData"
import MoreInsight from "@/components/common/MoreInsight"
import StartYourApp from "@/components/common/StartYourApp"
import Connect from "@/components/common/Connect"

export default function Home() {
 return (
  <>
   <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <main>
    <NavBar />
    <HeroSection />
    <CompanySlider />
    <Insight />
    <WayFromIdea />
    <GainInsight />
    <PowerOfData />
    <MoreInsight />
    <StartYourApp />
    <Connect />
    <FooterBar />
   </main>
  </>
 )
}
